customerSection=Customer
amountsSection=Amounts
customer=Customer
email=Billing email
website=Website
dueDate=Due date
currency=Currency
netAmount=Net amount
discount=Discount
taxRate=Tax rate
weight=Shipping weight
