OatCookieConsent.label=Consentimento de cookies
OatCookieConsent.message=Usamos cookies para que este site funcione e, com o seu consentimento, para melhorá-lo.
OatCookieConsent.accept=Aceitar
OatCookieConsent.necessary=Apenas os necessários
OatCookieConsent.policy=Política de privacidade
