OatCrud.new=Nuovo
OatCrud.edit=Modifica
OatCrud.delete=Elimina
OatCrud.save=Salva
OatCrud.newTitle=Nuova voce
OatCrud.editTitle=Modifica {0}
OatCrud.deleteQuestion=Eliminare {0}?
OatCrud.deleteDetail=Questa operazione non può essere annullata.
