OatCrud.new=Novo
OatCrud.edit=Editar
OatCrud.delete=Excluir
OatCrud.save=Salvar
OatCrud.newTitle=Novo registro
OatCrud.editTitle=Editar {0}
OatCrud.deleteQuestion=Excluir {0}?
OatCrud.deleteDetail=Esta ação não pode ser desfeita.
