OatCrud.new=Neu
OatCrud.edit=Bearbeiten
OatCrud.delete=Löschen
OatCrud.save=Speichern
OatCrud.newTitle=Neuer Eintrag
OatCrud.editTitle={0} bearbeiten
OatCrud.deleteQuestion={0} löschen?
OatCrud.deleteDetail=Dies kann nicht rückgängig gemacht werden.
