OatCookieConsent.label=Cookie-Einwilligung
OatCookieConsent.message=Wir verwenden Cookies, damit diese Website funktioniert, und mit Ihrer Zustimmung, um sie zu verbessern.
OatCookieConsent.accept=Akzeptieren
OatCookieConsent.necessary=Nur notwendige
OatCookieConsent.policy=Datenschutzerklärung
