OatCookieConsent.label=Cookietoestemming
OatCookieConsent.message=We gebruiken cookies om deze site te laten werken en, met uw toestemming, om hem te verbeteren.
OatCookieConsent.accept=Accepteren
OatCookieConsent.necessary=Alleen noodzakelijke
OatCookieConsent.policy=Privacybeleid
