OatCookieConsent.label=Cookie の同意
OatCookieConsent.message=このサイトの動作のため、また同意いただいた場合はサイト改善のために Cookie を使用します。
OatCookieConsent.accept=同意する
OatCookieConsent.necessary=必須のみ
OatCookieConsent.policy=プライバシーポリシー
