OatCrud.new=Nouveau
OatCrud.edit=Modifier
OatCrud.delete=Supprimer
OatCrud.save=Enregistrer
OatCrud.newTitle=Nouvelle entrée
OatCrud.editTitle=Modifier {0}
OatCrud.deleteQuestion=Supprimer {0} ?
OatCrud.deleteDetail=Cette action est irréversible.
