OatCrud.new=Nieuw
OatCrud.edit=Bewerken
OatCrud.delete=Verwijderen
OatCrud.save=Opslaan
OatCrud.newTitle=Nieuw item
OatCrud.editTitle={0} bewerken
OatCrud.deleteQuestion={0} verwijderen?
OatCrud.deleteDetail=Dit kan niet ongedaan worden gemaakt.
