OatCookieConsent.label=Consentement aux cookies
OatCookieConsent.message=Nous utilisons des cookies pour faire fonctionner ce site et, avec votre accord, pour l’améliorer.
OatCookieConsent.accept=Accepter
OatCookieConsent.necessary=Seulement les nécessaires
OatCookieConsent.policy=Politique de confidentialité
