OatCookieConsent.label=Consentimiento de cookies
OatCookieConsent.message=Usamos cookies para que este sitio funcione y, con su consentimiento, para mejorarlo.
OatCookieConsent.accept=Aceptar
OatCookieConsent.necessary=Solo las necesarias
OatCookieConsent.policy=Política de privacidad
