OatCookieConsent.label=Consenso ai cookie
OatCookieConsent.message=Usiamo i cookie per far funzionare questo sito e, con il tuo consenso, per migliorarlo.
OatCookieConsent.accept=Accetta
OatCookieConsent.necessary=Solo necessari
OatCookieConsent.policy=Informativa sulla privacy
