OatCrud.new=Nuevo
OatCrud.edit=Editar
OatCrud.delete=Eliminar
OatCrud.save=Guardar
OatCrud.newTitle=Nueva entrada
OatCrud.editTitle=Editar {0}
OatCrud.deleteQuestion=¿Eliminar {0}?
OatCrud.deleteDetail=Esta acción no se puede deshacer.
