OatCrud.new=New
OatCrud.edit=Edit
OatCrud.delete=Delete
OatCrud.save=Save
OatCrud.newTitle=New entry
OatCrud.editTitle=Edit {0}
OatCrud.deleteQuestion=Delete {0}?
OatCrud.deleteDetail=This can't be undone.
