OatDataTable.selected={0} sélectionné(s)
OatDataTable.clearSelection=Effacer la sélection
OatDataTable.selectAll=Sélectionner toutes les lignes de cette page
OatDataTable.selectRow=Sélectionner la ligne
OatActionsColumn.actions=Actions
OatDataTable.columns=Colonnes
OatDataTable.export=Exporter en CSV
OatDataTable.showDetails=Afficher les détails
OatDataTable.hideDetails=Masquer les détails
OatEditableColumn.edit=Modifier {0} : {1}
OatEditableColumn.save=Enregistrer
OatEditableColumn.cancel=Annuler
