OatDataTable.selected={0} ausgewählt
OatDataTable.clearSelection=Auswahl aufheben
OatDataTable.selectAll=Alle Zeilen dieser Seite auswählen
OatDataTable.selectRow=Zeile auswählen
OatActionsColumn.actions=Aktionen
OatDataTable.columns=Spalten
OatDataTable.export=Als CSV exportieren
OatDataTable.showDetails=Details anzeigen
OatDataTable.hideDetails=Details ausblenden
OatEditableColumn.edit={0} bearbeiten: {1}
OatEditableColumn.save=Speichern
OatEditableColumn.cancel=Abbrechen
