OatDataTable.selected={0} geselecteerd
OatDataTable.clearSelection=Selectie wissen
OatDataTable.selectAll=Alle rijen op deze pagina selecteren
OatDataTable.selectRow=Rij selecteren
OatActionsColumn.actions=Acties
