OatDataTable.selected=Seleccionados: {0}
OatDataTable.clearSelection=Quitar selección
OatDataTable.selectAll=Seleccionar todas las filas de esta página
OatDataTable.selectRow=Seleccionar fila
OatActionsColumn.actions=Acciones
