OatDataTable.selected={0} sélectionné(s)
OatDataTable.clearSelection=Effacer la sélection
OatDataTable.selectAll=Sélectionner toutes les lignes de cette page
OatDataTable.selectRow=Sélectionner la ligne
OatActionsColumn.actions=Actions
