OatDataTable.selected={0} selecionado(s)
OatDataTable.clearSelection=Limpar seleção
OatDataTable.selectAll=Selecionar todas as linhas desta página
OatDataTable.selectRow=Selecionar linha
OatActionsColumn.actions=Ações
