OatDataTable.selected={0} ausgewählt
OatDataTable.clearSelection=Auswahl aufheben
OatDataTable.selectAll=Alle Zeilen dieser Seite auswählen
OatDataTable.selectRow=Zeile auswählen
OatActionsColumn.actions=Aktionen
