OatDataTable.selected=Selezionati: {0}
OatDataTable.clearSelection=Cancella selezione
OatDataTable.selectAll=Seleziona tutte le righe di questa pagina
OatDataTable.selectRow=Seleziona riga
OatActionsColumn.actions=Azioni
