OatDataTable.selected={0} geselecteerd
OatDataTable.clearSelection=Selectie wissen
OatDataTable.selectAll=Alle rijen op deze pagina selecteren
OatDataTable.selectRow=Rij selecteren
OatActionsColumn.actions=Acties
OatDataTable.columns=Kolommen
OatDataTable.export=CSV exporteren
OatDataTable.showDetails=Details tonen
OatDataTable.hideDetails=Details verbergen
OatEditableColumn.edit={0} bewerken: {1}
OatEditableColumn.save=Opslaan
OatEditableColumn.cancel=Annuleren
