OatDataTable.selected=Selezionati: {0}
OatDataTable.clearSelection=Cancella selezione
OatDataTable.selectAll=Seleziona tutte le righe di questa pagina
OatDataTable.selectRow=Seleziona riga
OatActionsColumn.actions=Azioni
OatDataTable.columns=Colonne
OatDataTable.export=Esporta CSV
OatDataTable.showDetails=Mostra dettagli
OatDataTable.hideDetails=Nascondi dettagli
OatEditableColumn.edit=Modifica {0}: {1}
OatEditableColumn.save=Salva
OatEditableColumn.cancel=Annulla
