OatDataTable.selected={0} selecionado(s)
OatDataTable.clearSelection=Limpar seleção
OatDataTable.selectAll=Selecionar todas as linhas desta página
OatDataTable.selectRow=Selecionar linha
OatActionsColumn.actions=Ações
OatDataTable.columns=Colunas
OatDataTable.export=Exportar CSV
OatDataTable.showDetails=Mostrar detalhes
OatDataTable.hideDetails=Ocultar detalhes
OatEditableColumn.edit=Editar {0}: {1}
OatEditableColumn.save=Salvar
OatEditableColumn.cancel=Cancelar
