OatDataTable.selected=Seleccionados: {0}
OatDataTable.clearSelection=Quitar selección
OatDataTable.selectAll=Seleccionar todas las filas de esta página
OatDataTable.selectRow=Seleccionar fila
OatActionsColumn.actions=Acciones
OatDataTable.columns=Columnas
OatDataTable.export=Exportar CSV
OatDataTable.showDetails=Mostrar detalles
OatDataTable.hideDetails=Ocultar detalles
OatEditableColumn.edit=Editar {0}: {1}
OatEditableColumn.save=Guardar
OatEditableColumn.cancel=Cancelar
