OatLoginForm.username=Nome de usuário
OatLoginForm.password=Senha
OatLoginForm.rememberMe=Lembrar de mim
OatLoginForm.signIn=Entrar
OatLoginForm.failed=Nome de usuário ou senha incorretos.
OatLoginForm.forgotPassword=Esqueceu sua senha?
