OatLoginForm.username=Nome utente
OatLoginForm.password=Password
OatLoginForm.rememberMe=Ricordami
OatLoginForm.signIn=Accedi
OatLoginForm.failed=Nome utente o password errati.
OatLoginForm.forgotPassword=Password dimenticata?
