OatLoginForm.username=Username
OatLoginForm.password=Password
OatLoginForm.rememberMe=Remember me
OatLoginForm.signIn=Sign in
OatLoginForm.failed=Wrong username or password.
OatLoginForm.forgotPassword=Forgot your password?
