OatLoginForm.username=Nom d’utilisateur
OatLoginForm.password=Mot de passe
OatLoginForm.rememberMe=Se souvenir de moi
OatLoginForm.signIn=Se connecter
OatLoginForm.failed=Nom d’utilisateur ou mot de passe incorrect.
OatLoginForm.forgotPassword=Mot de passe oublié ?
