OatLoginForm.username=Gebruikersnaam
OatLoginForm.password=Wachtwoord
OatLoginForm.rememberMe=Ingelogd blijven
OatLoginForm.signIn=Inloggen
OatLoginForm.failed=Gebruikersnaam of wachtwoord onjuist.
OatLoginForm.forgotPassword=Wachtwoord vergeten?
