OatLoginForm.username=Benutzername
OatLoginForm.password=Passwort
OatLoginForm.rememberMe=Angemeldet bleiben
OatLoginForm.signIn=Anmelden
OatLoginForm.failed=Benutzername oder Passwort ist falsch.
OatLoginForm.forgotPassword=Passwort vergessen?
