OatLoginForm.username=Usuario
OatLoginForm.password=Contraseña
OatLoginForm.rememberMe=Recordarme
OatLoginForm.signIn=Iniciar sesión
OatLoginForm.failed=Usuario o contraseña incorrectos.
OatLoginForm.forgotPassword=¿Olvidó su contraseña?
