OatLoginForm.username=ユーザー名
OatLoginForm.password=パスワード
OatLoginForm.rememberMe=ログイン状態を保持
OatLoginForm.signIn=ログイン
OatLoginForm.failed=ユーザー名またはパスワードが正しくありません。
OatLoginForm.forgotPassword=パスワードをお忘れですか？
